apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - image: wordpress
    name: wordpress
    env:
    - name: password
      valueFrom:
        secretKeyRef:
          name: secr-name
          key: password
    - name: user
      valueFrom:
        secretKeyRef:
          name: secr-name
          key: user
